# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('adress', models.CharField(max_length=30, verbose_name='Улица')),
                ('adress_number', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('apartment', models.CharField(blank=True, max_length=10, verbose_name='Квартира')),
                ('entrance', models.PositiveIntegerField(blank=True, verbose_name='Подъезд')),
                ('floor', models.PositiveIntegerField(blank=True, verbose_name='Этаж')),
                ('order_status', models.CharField(choices=[('Новый', 'Новый'), ('Выполняется', 'Выполняется'), ('Завершен', 'Завершен')], default='Новый', max_length=10, verbose_name='Состояние заказа')),
                ('payment_status', models.CharField(choices=[('Нал', 'Наличные'), ('Карта', 'Cбербанк ОНЛАЙН')], max_length=30, verbose_name='Способ оплаты')),
                ('time_order', models.CharField(blank=True, max_length=5, verbose_name='Время заказа')),
                ('date_order', models.CharField(blank=True, max_length=10, verbose_name='Дата заказа')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='main.Product')),
            ],
        ),
    ]
