# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20171025_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Карта', 'Cбербанк ОНЛАЙН'), ('Нал', 'Наличные')], default='Нал', max_length=30, verbose_name='Способ оплаты'),
        ),
    ]
