# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20171025_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.CharField(blank=True, max_length=15, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Завершен', 'Завершен'), ('Новый', 'Новый'), ('Выполняется', 'Выполняется')], default='Новый', max_length=10, verbose_name='Состояние заказа'),
        ),
    ]
