# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20171025_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='entrance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='order',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Завершен', 'Завершен'), ('Выполняется', 'Выполняется'), ('Новый', 'Новый')], default='Новый', max_length=10, verbose_name='Состояние заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Нал', 'Наличные'), ('Карта', 'Cбербанк ОНЛАЙН')], default='Нал', max_length=30, verbose_name='Способ оплаты'),
        ),
    ]
