# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20171027_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='apartment',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Завершен', 'Завершен'), ('Выполняется', 'Выполняется')], default='Новый', max_length=20, verbose_name='Состояние заказа'),
        ),
    ]
