# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20171028_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couriers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя курьера')),
            ],
            options={
                'verbose_name': 'Курьер',
                'verbose_name_plural': 'Курьеры',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Выполняется', 'Выполняется'), ('Завершен', 'Завершен'), ('Новый', 'Новый')], default='Новый', max_length=20, verbose_name='Состояние заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.Couriers', verbose_name='Курьер'),
        ),
    ]
