# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20171030_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=144, max_digits=10, verbose_name='Оригинальная цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Карта', 'Cбербанк ОНЛАЙН'), ('Нал', 'Наличные')], default='Нал', max_length=30, verbose_name='Способ оплаты'),
        ),
    ]
